# Generated by Django 5.1.1 on 2024-09-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbero',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
    ]
